### ISSUE TITLE
Some problems while using

### ISSUE THREAD

**Issue by dimbtp** [admon84/screeps-tools#1]
Thanks for your tool and I have some issues while using in Firefox.
1. After adding one structure to the map and then remove it, you will get a blank content for this structureType while exporting.
    For example, start with a empty map, add a storage to the map and then remove it, you will get `"storage":{"pos":[]}` in your exported stuff, it's useless if you don't want to have it. (maybe not a big problem)
2. Why you prefer the new UI? I think the old one may be better.
    For example, I'm planing on level 8 and then switch to level7, I should remove some structures that need to be built later, you have to click the sub-menu and scroll every time you want to try another structure, you also do not have a good vision of whether I plan something wrong/more/less or not due to all these information are condensed in that menu.
3. A small problem when I remove `"world":"mmo"`, site will show empty content because it can not interpret the cached content.
   For example, I import `{"name":"","shard":"shard0","rcl":8,"buildings":{"storage":{"pos":[]}}}` without `"world":"mmo"`(because I don't use this key-value pair), it can work well until I close the tab and reopen it, it seems that it cannot interpret the local cached content and only display a black page. You have to clear locale cache to make it work.

English isn't my main language, sorry if you have trouble reading this issue.
Anyway, your tool is very helpful.

**Comment by admon84** [comment]
Thanks for the feedback.  I removed local cache stuff and resolved a few of these issues today
